#! /usr/bin/perl -w
use strict;
use File::Basename;
BEGIN { my $dir = dirname($0); unshift(@INC, "$dir", "$dir/perl_modules"); }

use Dahdi::Hardware;

my $hardware = Dahdi::Hardware->scan;
print join("\n", $hardware->drivers),"\n";
